apiVersion: v1
kind: ConfigMap
metadata:
  name: pricelab-config
  namespace: pricelab

data:
  SPRING_PROFILES_ACTIVE: "docker"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-service:5432/pricelab"
  SERVER_PORT: "8080"