spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/pricelab}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.validate-migration-naming=true

logging.level.org.flywaydb=DEBUG

logging.level.com.felipeboos=DEBUG
logging.level.org.springframework.web.client=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.reactor.netty.http.client=DEBUG