server.port=${PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/pricelab}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.validate-migration-naming=true

app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS:http://localhost:4200}

logging.level.org.flywaydb=INFO
logging.level.com.felipeboos=INFO
logging.level.org.springframework.web.client=INFO
logging.level.org.springframework.web=INFO
logging.level.reactor.netty.http.client=INFO

# ACTUATOR / MONITORING

# Expor endpoints necessários
management.endpoints.web.exposure.include=health,info,metrics,prometheus

# Mostrar detalhes de saúde (útil para debug)
management.endpoint.health.show-details=always

# Habilitar métricas Prometheus
management.prometheus.metrics.export.enabled=true

# (Opcional, mas recomendado) padronizar path
management.endpoints.web.base-path=/actuator